"""Serial.url(unique=True)

Revision ID: 6edc982e62b2
Revises: e1b7d994a101
Create Date: 2024-03-21 10:50:33.777881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6edc982e62b2"
down_revision: Union[str, None] = "e1b7d994a101"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "serials", ["url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "serials", type_="unique")
    # ### end Alembic commands ###
