"""empty message

Revision ID: e1b7d994a101
Revises: b8b675320368
Create Date: 2024-03-17 20:52:17.342042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1b7d994a101"
down_revision: Union[str, None] = "b8b675320368"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "serials", sa.Column("last_episode", sa.String(), nullable=True)
    )
    op.add_column(
        "serials", sa.Column("last_season", sa.String(), nullable=True)
    )
    op.alter_column(
        "users", "tracked_series", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "users", "watched_series", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "watched_series", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "users", "tracked_series", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("serials", "last_season")
    op.drop_column("serials", "last_episode")
    # ### end Alembic commands ###
