"""last_update: Serial_field

Revision ID: f76061e9082c
Revises: 6edc982e62b2
Create Date: 2024-03-22 10:13:58.434549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f76061e9082c"
down_revision: Union[str, None] = "6edc982e62b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "serials", sa.Column("last_update", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("serials", "last_update")
    # ### end Alembic commands ###
