name: Deploy Pipeline
on:
  pull_request:
    types:
      - closed
    branches:
      - master
    paths-ignore:
      - '.github/workflows/*'
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true

    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Copy .env file to remote server
        run: |
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SHH_KEY_TO_REMOTE_SERVER }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -avz --delete . root@${{ secrets.SSH_HOST }}:/watcher/

      - name: Start building
        run: ssh root@${{ secrets.SSH_HOST }} 'cd /watcher/ && docker-compose up -d --build'